### ISSUE TITLE
Best Practice Question: IPC using external component e.g. captive portal system service

### ISSUE THREAD

**Issue by MartinLoeper** [aws4embeddedlinux/meta-aws#1089]
Hi, I have a question regarding IPC on our Greengrass v2 device which is built using yocto.

We have a captive portal for initial device configuration (networking, provision by trusted user flow, etc.).
The captive portal is not deployed as a greengrass component.

The [greengrass v2 documentation regarding IPC](https://docs.aws.amazon.com/greengrass/v2/developerguide/interprocess-communication.html) sounds like IPC is only possible among components running inside the greengrass runtime. Is that interpretation correct?

If yes, is there an option to query deployment status from an external system service such as a captive portal?
I know that there is the greengrass-cli which is capable to do that. Is it possible to interface with the nucleus core from our captive portal just like the greengrass-cli binary does?

**Comment by nenadilic84** [comment]
Yes, that would definitely be possible.
To do this you would need to append files to the original greengrass recipe that adds the `greengrass-cli` component.

On which files you would need to add and their location I suggest you take a look at the installation after using the easy setup on, for example on ubuntu:

```
sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE \
  -jar ./GreengrassInstaller/lib/Greengrass.jar \
  --aws-region region \
  --thing-name MyGreengrassCore \
  --thing-group-name MyGreengrassCoreGroup \
  --thing-policy-name GreengrassV2IoTThingPolicy \
  --tes-role-name GreengrassV2TokenExchangeRole \
  --tes-role-alias-name GreengrassCoreTokenExchangeRoleAlias \
  --component-default-user ggc_user:ggc_group \
  --provision true \
  --setup-system-service true \
  --deploy-dev-tools true
```

Where you have the `  --deploy-dev-tools true` flag set.

This will provide the layout for packages directory that includes the `greengrass-cli`.

I tried this long time ago and it did work, but if you are doing this, please let me know as we might want to include this in the recipe as well.
