### ISSUE TITLE
Documentation for enabling aws-iot-device-client features

### ISSUE THREAD

**Issue by bawilless** [aws4embeddedlinux/meta-aws#1538]
I'm new to yocto and leveraging meta layers.  Can the team add some simple documentation to the meta-aws/recipes-iot/aws-iot-device-client folder with instructions for enabling a feature such as the aws-iot-device-client PubSub feature?

I can see the PACKAGECONFIG[] entries in the *.bb file, but I don't know what to do with them to enable the samples and pubsub features.

Thanks!

**Comment by thomas-roos** [comment]
Hi,
PACKAGECONFIG is a yocto common thing documented here: https://docs.yoctoproject.org/ref-manual/variables.html?highlight=packageconfig#term-PACKAGECONFIG
-> to enable samples and pubsub feature you can put 
PACKAGECONFIG:aws-iot-device-client = "samples pubsub"
into your local.conf
Hope this helps.
