### ISSUE TITLE
Greengrass v2.3.0 for Hardknott

### ISSUE THREAD

**Issue by rpcme** [aws4embeddedlinux/meta-aws#163]
Customer has reached out for latest Greengrass v2 support on Hardknott since the NXP IMx8 BSP is aligned with the Hardknott release.

Please propagate and validate the recipes to this release branch to support the customer.

**Comment by K-AWS** [comment]
Hi Richard,
Thanks for reporting the issue. We've opened a backlog item to add the recent Greengrass recipes to Hardknott.
Thanks,

**Comment by rpcme** [comment]
Hello @K-AWS any update?

**Comment by rpcme** [comment]
Hello @K-AWS any update?

**Comment by K-AWS** [comment]
Closing request since PR was merged.
