### ISSUE TITLE
Devtool development flow isn't working for greengrass-bin (dunfell-next)

### ISSUE THREAD

**Issue by pwillem** [aws4embeddedlinux/meta-aws#3145]
Hello

I am trying to use [devtool](https://docs.yoctoproject.org/3.1.24/ref-manual/ref-devtool-reference.html?highlight=devtool) to modify the `greengrass-bin` recipe but the `devtool build greengrass-bin` step fails with the following error `install: cannot stat '/image/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/greengrass-bin/2.9.4-r0/LICENSE': No such file or directory   `.  Running `bitbake greengrass-bin` builds the recipe without an issue.

Steps to reproduce:
1. Create a dunfell build environment
2. `source poky/oe-init-build-env`
3. `devtool modify greengrass-bin`
4. `devtool build  greengrass-bin`
->  this fails with `install: cannot stat 'image/build/tmp/work/armv7vet2hf-neon-poky-linux-gnueabi/greengrass-bin/2.9.4-r0/LICENSE': No such file or directory`

I could solve it with this [patch](https://github.com/pwillem/meta-aws/commit/56e21ffe8a69a52526a6a4ac6fb42dd024a22d02).
Using  `${S}` is also what the poky binary installation helper class uses [bin_package.bbclass](https://github.com/yoctoproject/poky/blob/dunfell/meta/classes/bin_package.bbclass).

Bootlin has an interesting slide in their yocto training material about the different variable names
![image](https://user-images.githubusercontent.com/18293436/229359011-2e8298d9-ff0a-4f1a-b727-99bf13b77f61.png)

**Comment by thomas-roos** [comment]
Thank you! Will fix this today.
