### ISSUE TITLE
commit squashing

### ISSUE THREAD

**Issue by jwinarske** [aws4embeddedlinux/meta-aws#319]
Any reason why my contribution commits for (rust recipes) were squashed?  It no longer lists me as a contributor.

**Comment by nateglims** [comment]
I do not know where it got lost, however I almost certainly personally made the change and I'd like to apologize.

I have removed the ability to squash in the github interface and rewritten our release process to use FF-only merges to prevent this and other issues.

We will be publishing our release process changes for transparency in the near future.
