### ISSUE TITLE
Improve arm64 tuning

### ISSUE THREAD

**Issue by rossburton** [aws4embeddedlinux/meta-aws#6534]
The default tune for the `aws-ec2-arm64` machine is v8.0, which might have been true for graviton1 but isn't optimal for graviton3 and certainly isn't for graviton4 (which is speculated as having Arm V2 cores, so supports v9).

**Comment by thomas-roos** [comment]
Hi Ross, thanks for pointing this out. Will fix asap.
Cheers, Thomas

**Comment by thomas-roos** [comment]
This is a good overview and mapping instance type to Graviton version to instruction sets.
https://en.wikipedia.org/wiki/AWS_Graviton
-> decided to go for arch-armv8-2a by now
