### ISSUE TITLE
meta-aws is not available for krogoth branch

### ISSUE THREAD

**Issue by sushmad16** [aws4embeddedlinux/meta-aws#9418]
I am currently using the Krogoth branch of OpenEmbedded and would like to integrate the meta-aws layer. However, it appears that meta-aws is not available for this branch.

Could you please confirm if there are plans to support meta-aws for the Krogoth branch? If not, are there any recommended alternatives for integrating aws with Krogoth.

**Comment by thomas-roos** [comment]
Hi, no plans to support this. As this is EOL. https://wiki.yoctoproject.org/wiki/Releases

**Comment by sushmad16** [comment]
> Hi, no plans to support this. As this is EOL long ago. https://wiki.yoctoproject.org/wiki/Releases

Thanks for the response Thomas
