### ISSUE TITLE
SRC_URI Checksum incorrect in Corretto 11.0.24.8.1 recipe

### ISSUE THREAD

**Issue by okt0** [aws4embeddedlinux/meta-aws#9441]
Hi,
it appears that the checksum used for the Corretto 11.0.24.8.1 ARM archive is incorrect. The current checksum matches version 11.0.20.9.1 instead (https://corretto.aws/downloads/resources/11.0.20.9.1/amazon-corretto-11.0.20.9.1-linux-armv7.tar.gz)

**Comment by thomas-roos** [comment]
Thank you for reporting. Will look into that next week after being back from vacation.

**Comment by thomas-roos** [comment]
Thank you for reporting, fixed in linked commit.
